export const MOCK_PRODUCTS = [
    {
        id: 1,
        name: "Amethyst Cluster",
        price: 45.0,
        category: "Crystal",
        image: "🟣",
        purpose: "Protection",
        rating: 5,
        reviewsCount: 12,
        stock: 15,
        images: ["🟣", "✨", "💜", "🌌"],
        shortDescription: "Elevate your spiritual journey with this ethically sourced Amethyst Cluster. Crafted by nature to bring balance, intuition, and protective harmony to your sacred space.",
        description: "This exceptional piece has been carefully hand-selected for its unique energy signature and physical beauty. Amethyst is renowned as a stone of spiritual protection and purification, cleansing one's energy field of negative influences and attachments. It creates a resonant shield of spiritual Light around the body, acting as a barrier against lower energies, psychic attack, geopathic stress, and unhealthy environments.",
        chakra: "Third Eye, Crown & Etheric",
        zodiac: "Pisces, Virgo, Aquarius & Capricorn",
        element: "Wind",
    },
    {
        id: 2,
        name: "Rose Quartz Wand",
        price: 30.0,
        category: "Healing Tool",
        image: "🌸",
        purpose: "Love",
        rating: 5,
        reviewsCount: 8,
        stock: 20,
        images: ["🌸", "💗", "✨", "🎀"],
        shortDescription: "The absolute stone of unconditional love. This Rose Quartz pointed wand is perfect for directing healing energy and opening the heart.",
        description: "Carved from premium Madagascar Rose Quartz, this massage and energy wand gently draws off negative energy and replaces it with loving vibrations. It strengthens empathy and sensitivity, and aids in the acceptance of necessary change. An excellent stone for comforting grief and encouraging self-forgiveness and acceptance.",
        chakra: "Heart",
        zodiac: "Taurus & Libra",
        element: "Water",
    },
    {
        id: 3,
        name: "Clear Quartz Sphere",
        price: 65.0,
        category: "Crystal",
        image: "⚪",
        purpose: "Healing",
        rating: 5,
        reviewsCount: 15,
        stock: 5,
        images: ["⚪", "🔮", "✨", "🧊"],
        shortDescription: "A master healer. This perfectly polished sphere radiates energy in all directions, amplifying intention and bringing supreme clarity.",
        description: "Clear Quartz is known as the 'master healer' and will amplify energy and thought, as well as the effect of other crystals. It absorbs, stores, releases and regulates energy. Clear Quartz draws off negative energy of all kinds. It balances and revitalizes the physical, mental, emotional and spiritual planes.",
        chakra: "Crown (Harmonizes All Chakras)",
        zodiac: "All Signs",
        element: "All Elements",
    },
    {
        id: 4,
        name: "Mystic Tarot Deck",
        price: 40.0,
        category: "Divination",
        image: "🃏",
        purpose: "Intuition",
        rating: 4,
        reviewsCount: 32,
        stock: 50,
        images: ["🃏", "🎴", "👁️", "✨"],
        shortDescription: "Unlock the secrets of the universe with our custom-illustrated 78-card Tarot deck. Rich with symbolism and intuitive cues.",
        description: "This modern interpretation of the classic Rider-Waite-Smith system features stunning, dreamlike artwork designed to bypass the conscious mind and speak directly to your intuition. Printed on premium, thick cardstock with a matte finish and gilded edges. Includes a comprehensive 120-page guidebook.",
        chakra: "Third Eye",
        zodiac: "All Signs",
        element: "Ether / Spirit",
    },
    {
        id: 5,
        name: "Citrine Point",
        price: 25.0,
        category: "Crystal",
        image: "💛",
        purpose: "Wealth",
        rating: 4,
        reviewsCount: 19,
        stock: 12,
        images: ["💛", "☀️", "💰", "✨"],
        shortDescription: "The merchant's stone. This natural Citrine point is a powerful attractor of wealth, prosperity, and success.",
        description: "Genuine unheated Citrine from Brazil. Citrine is a premier stone of manifestation, imagination, and personal will. Carrying the power of the sun, it is warm and comforting, energizing and life-giving. It stimulates the chakras like the sunlight of spring, clearing the mind and stirring the soul to action. It never needs cleansing as it does not hold negative energy.",
        chakra: "Solar Plexus & Sacral",
        zodiac: "Aries, Gemini, Leo, Libra",
        element: "Fire",
    },
    {
        id: 6,
        name: "Obsidian Pyramid",
        price: 55.0,
        category: "Crystal",
        image: "🖤",
        purpose: "Protection",
        rating: 5,
        reviewsCount: 24,
        stock: 8,
        images: ["🖤", "🔺", "👁️‍🗨️", "🌑"],
        shortDescription: "A powerful energetic shield. The pyramid shape amplifies Obsidian's natural grounding and protective properties.",
        description: "Black Obsidian is a glorious stone for power, protection, and grounding. It is a strongly protective stone, forming a shield against negativity. It blocks psychic attack and absorbs negative energies from the environment. Obsidian draws out mental stress and tension, stimulating growth on all levels and urging exploration of the unknown.",
        chakra: "Root",
        zodiac: "Scorpio, Sagittarius",
        element: "Earth & Fire",
    },
    {
        id: 7,
        name: "Sage Smudge Stick",
        price: 15.0,
        category: "Healing Tool",
        image: "🌿",
        purpose: "Healing",
        rating: 5,
        reviewsCount: 112,
        stock: 200,
        images: ["🌿", "💨", "✨", "🔥"],
        shortDescription: "Traditionally bundled White Sage for clearing stagnant energy from your home, aura, or sacred objects.",
        description: "Our White Sage is sustainably and ethically harvested from private land in California. Smudging with sage is an ancient practice utilized for centuries to clear negative energies, bless spaces, and prepare for ceremony. Each bundle is hand-tied with organic cotton string.",
        chakra: "All Chakras",
        zodiac: "All Signs",
        element: "Air & Earth",
    },
    {
        id: 8,
        name: "Selenite Tower",
        price: 35.0,
        category: "Crystal",
        image: "🤍",
        purpose: "Intuition",
        rating: 4,
        reviewsCount: 45,
        stock: 30,
        images: ["🤍", "🏛️", "✨", "☁️"],
        shortDescription: "A pillar of pure white light. Perfect for creating a protective grid around your home or cleansing other stones.",
        description: "Selenite is a crystallized form of Gypsum, known for its pristine white, luminous appearance. It brings clarity of mind, opening the crown and higher crown chakras and accessing angelic consciousness and higher guidance. Pure Selenite is a link to the lightbody, helping to anchor it in the earth vibration. It is one of the most powerful crystals for the new vibration on earth.",
        chakra: "Crown",
        zodiac: "Taurus",
        element: "Wind",
    },
    {
        id: 9,
        name: "Oracle Cards",
        price: 38.0,
        category: "Divination",
        image: "🎴",
        purpose: "Intuition",
        rating: 5,
        reviewsCount: 22,
        stock: 45,
        images: ["🎴", "🦋", "🌙", "✨"],
        shortDescription: "Gentle daily guidance. This 44-card oracle deck delivers profound insights and supportive messages from the universe.",
        description: "Unlike Tarot, which follows a structured system, these Oracle cards are free-flowing and deeply intuitive. Each card features an archetype, animal guide, or element of nature, alongside a brief supportive message. The accompanying guidebook provides deeper meanings and suggested card spreads for daily alignment.",
        chakra: "Third Eye & Heart",
        zodiac: "All Signs",
        element: "Ether",
    },
    {
        id: 10,
        name: "Tiger's Eye Bracelet",
        price: 28.0,
        category: "Jewelry",
        image: "🐯",
        purpose: "Wealth",
        rating: 5,
        reviewsCount: 67,
        stock: 18,
        images: ["🐯", "📿", "👁️", "✨"],
        shortDescription: "Wear the stone of courage, power, and wealth. This stretch bracelet keeps grounded confidence with you all day.",
        description: "Smooth, 8mm golden Tiger's Eye beads strung on strong elastic. A stone of protection, Tiger Eye may also bring good luck to the wearer. It has the power to focus the mind, promoting mental clarity, assisting us to resolve problems objectively and unclouded by emotions. Particularly useful for healing psychosomatic illnesses, dispelling fear and anxiety.",
        chakra: "Solar Plexus, Root & Sacral",
        zodiac: "Capricorn",
        element: "Earth & Fire",
    },
    {
        id: 11,
        name: "Green Aventurine",
        price: 18.0,
        category: "Crystal",
        image: "💚",
        purpose: "Wealth",
        rating: 4,
        reviewsCount: 14,
        stock: 25,
        images: ["💚", "🍀", "✨", "💰"],
        shortDescription: "The 'Stone of Opportunity', thought to be the luckiest of all crystals, especially in manifesting prosperity.",
        description: "This tumbled Green Aventurine piece is perfect for carrying in your pocket or placing in a cash box. Its winning energy makes it a great ally for boosting one’s chances in any situation. It is also a comforter and heart healer. It neutralizes all sources of electromagnetic pollution, blocking out emanations from computers, television and other electronic equipment.",
        chakra: "Heart",
        zodiac: "Aries, Leo",
        element: "Earth",
    },
    {
        id: 12,
        name: "Pendulum Board",
        price: 45.0,
        category: "Divination",
        image: "🔮",
        purpose: "Intuition",
        rating: 5,
        reviewsCount: 9,
        stock: 6,
        images: ["🔮", "🪵", "✨", "🧭"],
        shortDescription: "A beautifully engraved wooden resting place and guide for your pendulum work.",
        description: "Crafted from solid birch wood and laser engraved with 'Yes/No', letters, numbers, and astrological symbols. This board provides a clear visual map for receiving detailed answers from your higher self and spirit guides during pendulum divination sessions.",
        chakra: "Third Eye",
        zodiac: "All Signs",
        element: "Wood / Earth",
    },
    {
        id: 13,
        name: "Chakra Healing Set",
        price: 85.0,
        category: "Healing Tool",
        image: "🌈",
        purpose: "Healing",
        rating: 5,
        reviewsCount: 56,
        stock: 2,
        images: ["🌈", "💎", "✨", "🧘‍♀️"],
        shortDescription: "A complete set of 7 tumbled stones corresponding to the major chakras, nestled in a wooden sacred geometry box.",
        description: "Includes Root (Red Jasper), Sacral (Carnelian), Solar Plexus (Citrine), Heart (Green Aventurine), Throat (Sodalite), Third Eye (Amethyst), and Crown (Clear Quartz). Use this set to balance and align your energy centers. Perfect for meditation, reiki practice, or placing on the body during rest.",
        chakra: "All Chakras",
        zodiac: "All Signs",
        element: "All Elements",
    },
    {
        id: 14,
        name: "Moonstone Ring",
        price: 95.0,
        category: "Jewelry",
        image: "🌙",
        purpose: "Love",
        rating: 5,
        reviewsCount: 31,
        stock: 14,
        images: ["🌙", "💍", "✨", "🤍"],
        shortDescription: "Handcrafted sterling silver ring featuring an iridescent Rainbow Moonstone cabochon.",
        description: "A stone for 'new beginnings', Moonstone is a stone of inner growth and strength. It soothes emotional instability and stress, and stabilizes the emotions, providing calmness. Moonstone enhances intuition, promotes inspiration, success and good fortune in love and business matters.",
        chakra: "Sacral, Third Eye, Crown",
        zodiac: "Cancer, Libra, Scorpio",
        element: "Water",
    },
    {
        id: 15,
        name: "Lapis Lazuli Raw",
        price: 42.0,
        category: "Crystal",
        image: "💙",
        purpose: "Intuition",
        rating: 4,
        reviewsCount: 20,
        stock: 15,
        images: ["💙", "🌌", "✨", "👁️"],
        shortDescription: "The stone of royalty and spirituality. This raw chunk reveals deep celestial blues and golden pyrite flecks.",
        description: "Lapis Lazuli is one of the most sought after stones in use since man's history began. Its deep, celestial blue remains the symbol of royalty and honor, gods and power, spirit and vision. It is a universal symbol of wisdom and truth. It stimulates enlightenment and enhances dream work and psychic abilities.",
        chakra: "Throat & Third Eye",
        zodiac: "Sagittarius",
        element: "Water & Wind",
    },
    {
        id: 16,
        name: "Palo Santo Bundles",
        price: 20.0,
        category: "Healing Tool",
        image: "🪵",
        purpose: "Protection",
        rating: 5,
        reviewsCount: 88,
        stock: 100,
        images: ["🪵", "🔥", "✨", "💨"],
        shortDescription: "Premium 'Holy Wood' from Peru. Sweet, grounding scent for uplifting your vibration.",
        description: "Our Palo Santo is 100% sustainably and ethically sourced from naturally fallen trees in Peru. We never cut down living trees. Lighting a stick of Palo Santo produces a sweet, piney, lemony smoke that clears negative energy, restores tranquility and calms emotions.",
        chakra: "Root & Crown",
        zodiac: "Gemini, Virgo, Aquarius",
        element: "Air & Fire",
    },
    {
        id: 17,
        name: "Malachite Heart",
        price: 60.0,
        category: "Crystal",
        image: "💚",
        purpose: "Love",
        rating: 5,
        reviewsCount: 7,
        stock: 4,
        images: ["💚", "🌿", "✨", "🎭"],
        shortDescription: "A powerful stone of transformation carved into a smooth heart to open and protect the heart center.",
        description: "Malachite is a stone of balance, abundance, manifestation and intention. An extremely powerful metaphysical stone, Malachite is often called the 'stone of transformation' and is used for deep energy cleaning, bringing healing and positive transformation to the wearer. It protects against the 'Evil Eye' and negative magic.",
        chakra: "Heart & Solar Plexus",
        zodiac: "Scorpio & Capricorn",
        element: "Earth",
    },
    {
        id: 18,
        name: "Astrology Digest",
        price: 30.0,
        category: "Divination",
        image: "⭐",
        purpose: "Intuition",
        rating: 4,
        reviewsCount: 15,
        stock: 60,
        images: ["⭐", "🪐", "📜", "✨"],
        shortDescription: "A comprehensive yearly guide to planetary transits and how to harness their energies.",
        description: "This premium 200-page almanac features detailed breakdowns of retrograde periods, new and full moons, eclipses, and major planetary aspects. Includes rituals tailored to each astrological season and space for your own cosmic journaling.",
        chakra: "Third Eye",
        zodiac: "All Signs",
        element: "Air & Ether",
    },
    {
        id: 19,
        name: "Singing Bowl",
        price: 120.0,
        category: "Healing Tool",
        image: "🥣",
        purpose: "Healing",
        rating: 5,
        reviewsCount: 42,
        stock: 10,
        images: ["🥣", "🎶", "✨", "🧘"],
        shortDescription: "A hand-hammered brass singing bowl from Nepal, producing deep, resonant frequencies for sound healing.",
        description: "The vibrations produced by this bowl penetrate deeply into the body, harmonizing cellular structure and calming the nervous system. The sound facilitates deep meditation, stress reduction, and balances the chakras. Comes with a wooden mallet and a decorative silk cushion.",
        chakra: "All Chakras",
        zodiac: "All Signs",
        element: "Sound / Ether",
    },
    {
        id: 20,
        name: "Black Tourmaline",
        price: 22.0,
        category: "Crystal",
        image: "⬛",
        purpose: "Protection",
        rating: 5,
        reviewsCount: 51,
        stock: 0,
        images: ["⬛", "🛡️", "✨", "🌑"],
        shortDescription: "The ultimate bodyguard stone. Place near entrances or carry with you to absorb and repel negative vibrations.",
        description: "A premier stone of protection and grounding, Black Tourmaline cleanses, purifies, and transforms dense energy into a lighter vibration. It grounds spiritual energy, clears and balances all the chakras, and forms a protective shield around the body. It is highly useful in purifying one's own thoughts as well as the immediate environment.",
        chakra: "Root",
        zodiac: "Libra",
        element: "Earth",
    },
];
